# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$PATH:/usr/sbin
# source $HOME/antigen.zsh

# # Path to your oh-my-zsh installation.
# export ZSH="$HOME/.oh-my-zsh"

# ZSH_THEME="pure"
# plugins=(git)

# source $ZSH/oh-my-zsh.sh
# export TERM=xterm-256color

source $HOME/antigen.zsh

antigen use oh-my-zsh

# Récupération de "bundles" depuis la librairie par défaut
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle docker-compose
antigen bundle github
antigen bundle colorize

# Récupération de "bundles"
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

# Ajout d'un thème.
antigen theme sindresorhus/pure

# Appliquer l'ensemble des changements
antigen apply

# style pure theme
zstyle ':prompt:pure:prompt:*' color blue
zstyle ':prompt:pure:prompt:error' color red
zstyle ':prompt:pure:path' color white
export PURE_PROMPT_SYMBOL="»"
