#!/bin/sh
### BEGIN INIT INFO
# Provides:          enable_wifi_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Enable wifi blocked by defaut with rfkill
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting enable_wifi_once"
    rfkill unblock 0
    update-rc.d enable_wifi_once remove &&
    rm /etc/init.d/enable_wifi_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
